name: CI/CD Pipeline - Build & Push Docker Images

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows you to run this manually from GitHub button

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Check out the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx (Required for caching)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build & Push BACKEND
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/devops-tier3-kubernetes-deployment-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/devops-tier3-kubernetes-deployment-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 5. Build & Push FRONTEND
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/devops-tier3-kubernetes-deployment-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/devops-tier3-kubernetes-deployment-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max